const data = {
  products: [
    {
      _id: "1",
      name: "Nike Slim Shirt",
      category: "Baum",
      image: "/images/product-2.jpg",
      price: 120,
      brand: "foto",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "2",
      name: " Slim Shirt",
      category: "Baum",
      image: "/images/product-2.jpg",
      price: 120,
      brand: "foto",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "3",
      name: "Nike Slim Shirt",
      category: "Baum",
      image: "/images/product-2.jpg",
      price: 120,
      brand: "foto",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "Nike Slim Shirt",
      category: "Baum",
      image: "/images/product-2.jpg",
      price: 120,
      brand: "foto",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "5",
      name: "Nike Slim Shirt",
      category: "Baum",
      image: "/images/product-2.jpg",
      price: 120,
      brand: "foto",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
  ],
};
export default data;
